In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Importing the necessary libraries

In [4]:
import numpy as np
import os
import pandas as pd
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf
import keras
from keras import layers
import numpy as np
from keras.layers import Conv2D, Dense, Flatten, Dropout, MaxPooling2D
from keras.models import Sequential, save_model
from keras.utils import np_utils
from keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import os
import cv2
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model,load_model
from keras.layers import Input, Dense, Add,Activation, AveragePooling2D, BatchNormalization, Flatten, Conv2D, MaxPooling2D, Dropout, ZeroPadding2D
from keras.utils import to_categorical
from keras.initializers import glorot_uniform
from keras import regularizers
import scipy.misc
from sklearn.model_selection import train_test_split


In [10]:
root_directory="/content/drive/MyDrive/DATASETS/"
survival_words_directory="/content/drive/MyDrive/DATASETS/25_survival_words/"
alphabets_directory="/content/drive/MyDrive/DATASETS/ALPHABETS/"
numbers_directory="/content/drive/MyDrive/DATASETS/NUMBERS/"

In [6]:
k=0

Creating numpy arrays of elements an labelling array

In [7]:
def load_dataset(directory,k):
  images=[]
  labels=[]
  for idx,label in enumerate(uniq_labels):
    for file in os.listdir(directory + label):
      filepath = directory + label +"/" + file
      img = cv2.resize(cv2.imread(filepath),(50,50))
      images.append(img)
      labels.append(k)
    k+=1
  images = np.asarray(images)
  labels = np.asarray(labels)
  return images, labels,k

In [8]:
# uniq_labels=sorted(os.listdir(alphabets_directory))
# print(uniq_labels)

In [11]:
uniq_labels=sorted(os.listdir(numbers_directory))
X_numbers_directory,y_numbers_directory,k=load_dataset(numbers_directory,k)

In [ ]:
# /content/drive/MyDrive/DATASETS/NUMBERS

In [12]:
y_numbers_directory


array([0, 0, 0, ..., 9, 9, 9])

In [13]:
uniq_labels=sorted(os.listdir(alphabets_directory))
X_alphabets_directory,y_alphabets_directory,k=load_dataset(alphabets_directory,k)

In [14]:
y_alphabets_directory

array([10, 10, 10, ..., 34, 34, 34])

In [15]:
uniq_labels=sorted(os.listdir(survival_words_directory))
X_survival_words_directory,y_survival_words_directory,k=load_dataset(survival_words_directory,k)

In [16]:
y_survival_words_directory

array([35, 35, 35, ..., 59, 59, 59])

In [17]:
X=[]
y=[]

In [18]:
X=np.concatenate((X_numbers_directory,X_alphabets_directory))

In [19]:
X=np.concatenate((X,X_survival_words_directory))

In [20]:
y=np.concatenate((y_numbers_directory,y_alphabets_directory))

In [21]:
y=np.concatenate((y,y_survival_words_directory))

In [22]:
y

array([ 0,  0,  0, ..., 59, 59, 59])

In [23]:
# list(y.keys())
y = to_categorical(y)


In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2)

In [25]:
X_train = X_train / 255.
X_test = X_test/ 255.

CNN Model

In [26]:
model = Sequential()
model.add(Conv2D(64, kernel_size=(3,3), activation = 'relu', input_shape=(50,50,3) ))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Conv2D(64, kernel_size = (3, 3), activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Conv2D(64, kernel_size = (3, 3), activation = 'relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Flatten())
model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.20))
model.add(Dense(y.shape[1], activation = 'softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 48, 48, 64)        1792      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 24, 24, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 22, 22, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 11, 11, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 9, 9, 64)          36928     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 4, 4, 64)         0

In [27]:
y.shape

(11600, 60)

In [28]:
np.unique(y)

array([0., 1.], dtype=float32)

In [29]:
model.compile(optimizer='Adam', metrics=['accuracy'], loss='categorical_crossentropy')

Fitting the Model

In [30]:
fit = model.fit(X_train, Y_train, batch_size=138, epochs=100)

Epoch 1/100
68/68 [==============================] - 10s 18ms/step - loss: 3.3772 - accuracy: 0.1950
Epoch 2/100
68/68 [==============================] - 1s 16ms/step - loss: 0.9123 - accuracy: 0.7781
Epoch 3/100
68/68 [==============================] - 1s 16ms/step - loss: 0.3009 - accuracy: 0.9231
Epoch 4/100
68/68 [==============================] - 1s 16ms/step - loss: 0.1549 - accuracy: 0.9586
Epoch 5/100
68/68 [==============================] - 1s 16ms/step - loss: 0.0816 - accuracy: 0.9789
Epoch 6/100
68/68 [==============================] - 1s 16ms/step - loss: 0.0605 - accuracy: 0.9834
Epoch 7/100
68/68 [==============================] - 1s 16ms/step - loss: 0.0423 - accuracy: 0.9877
Epoch 8/100
68/68 [==============================] - 1s 16ms/step - loss: 0.0347 - accuracy: 0.9893
Epoch 9/100
68/68 [==============================] - 1s 16ms/step - loss: 0.0290 - accuracy: 0.9901
Epoch 10/100
68/68 [==============================] - 1s 16ms/step - loss: 0.0236 - accuracy: 0.992

In [31]:
y_pred = model.predict(X_test)

73/73 [==============================] - 0s 4ms/step


In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_pred.round())*100

99.95689655172414

In [33]:
from sklearn.metrics import classification_report, confusion_matrix

In [34]:
print(classification_report(y_pred.round(), Y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        75
           1       1.00      1.00      1.00        58
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        61
           4       1.00      1.00      1.00        64
           5       1.00      1.00      1.00        59
           6       1.00      1.00      1.00        21
           7       0.96      1.00      0.98        24
           8       1.00      1.00      1.00        13
           9       1.00      1.00      1.00        20
          10       1.00      1.00      1.00        77
          11       1.00      1.00      1.00        75
          12       1.00      1.00      1.00        60
          13       1.00      1.00      1.00        19
          14       1.00      1.00      1.00        16
          15       1.00      1.00      1.00        23
          16       1.00      1.00      1.00        20
          17       1.00    

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [35]:
accuracy = model.evaluate(X_test,Y_test,batch_size=138)
print("Accuracy: ",accuracy[1]*100)

17/17 [==============================] - 0s 15ms/step - loss: 0.0019 - accuracy: 0.9996
Accuracy:  99.95689392089844


In [36]:
# model.save_weights('/content/drive/MyDrive/Freelance/NomanRafique/')
model.save('my_model.h5') 


In [37]:
model.save('/content/drive/MyDrive/my_model.h5') 